// <auto-generated />
namespace Cars.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Car_Mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Car_Mig));
        
        string IMigrationMetadata.Id
        {
            get { return "202301271736419_Car_Mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
